var btn=$.fn.button.noConflict();$.fn.btn=btn;var inputsChanged=!1;$(document).ready(function(){startUpFunctions();Sys.WebForms.PageRequestManager.getInstance().add_beginRequest(beginRequest);Sys.WebForms.PageRequestManager.getInstance().add_endRequest(endRequest);Sys.WebForms.PageRequestManager.getInstance().add_endRequest(startUpFunctions)});function beginRequest(a,b){ShowUpdateProgress()}
function endRequest(a,b){HideUpdateProgress();var c=b.get_error();null!=c?(b.set_errorHandled(!0),-1==c.message.indexOf("VALIDACAO")?AlertaErro("<strong>Ocorreu um erro no sistema!</strong> Favor entrar em contato com a \u00e1rea respons\u00e1vel."):(b.set_errorHandled(!0),AlertaValidacao(""+c.message.replace("Sys.WebForms.PageRequestManagerServerErrorException: VALIDACAO:","")))):$("#div-alerta-erro").remove()}
function ShowUpdateProgress(){$('<div id="UpdateProgress" style="text-align:center;"><img src="/PMS/Imagens/ajax-loader.gif" /><br />Carregando</div>').dialog({height:78,width:100,modal:!0,resizable:!1,zIndex:1090,dialogClass:"no-close progress"})}function HideUpdateProgress(){$("#UpdateProgress").remove()}
function startUpFunctions(){inputsChanged=!1;$(window).scroll(function(){if(0<$(".progress").length){var a=$(document).scrollTop()+$(document).height()/2-$(".progress").width()+"px";$(".progress").animate({top:a},{duration:500,queue:!1})}});$("form input, textarea, select").change(function(){inputsChanged=!0});$("form input").attr("autocomplete","off");$(".textarea[maxlength]").unbind("keydown");$("textarea[maxlength]").keydown(function(a){return!$(this).attr("maxlength")||this.value.length<$(this).attr("maxlength")||
8==a.keyCode||46==a.keyCode}).keyup(function(a){if(a=$(this).attr("maxlength")){if(this.value.length<=a)return!0;this.value=this.value.substr(0,a);return!1}});$(".cancel").click(function(){if(inputsChanged)return $(this).confirmModal({heading:"Confirma\u00e7\u00e3o",body:"Tem certeza que deseja cancelar a opera\u00e7\u00e3o?"}),!1});$(".excluir").click(function(){$(this).confirmModal({heading:"Confirma\u00e7\u00e3o",body:"Deseja realmente excluir o registro?"});return!1});"undefined"!=typeof Page_Validators&&
$.each(Page_Validators,function(a,b){$("#"+b.id).attrchange({trackValues:!0,callback:function(a){0<=a.newValue.indexOf("inline")?$(this).mostrarErro():$(this).removerErro()}})});$(".accordion").accordion({collapsible:!0});$(".data").datepicker({changeMonth:!0,changeYear:!0,dateFormat:"dd/mm/yy"});$(".data").unbind("blur");$(".data").mask("99/99/9999");$(".data").blur(function(){$(this).removerErro({classe:"datainvalida"});""==$(this).val()||isData($(this).val())||($(this).mostrarErro({classe:"datainvalida",
texto:"Data inv\u00e1lida."}),$(this).focus())});$(".email").unbind("blur");$(".email").change(function(){$(this).removerErro({classe:"emailInvalido"});""==$(this).val()||isEmail($(this).val())||($(this).mostrarErro({classe:"emailInvalido",texto:"Email inv\u00e1lido."}),$(this).focus())});$(".hora").unbind("blur");$(".hora").mask("99:99");$(".hora").blur(function(){$(this).removerErro({classe:"horainvalida"});""==$(this).val()||isHora($(this).val())||($(this).mostrarErro({classe:"horainvalida",texto:"Hora inv\u00e1lida."}),
$(this).focus())});$(".cpf").unbind("change");$(".cpf").mask("?999.999.999-99");$(".cpf").bind("change",function(){$(this).parents(".form-group").removeClass("has-error");$(this).parents(".form-element").removeClass("has-error");$(".cfpinvalido").remove();isCPF($(this).val())||($(this).parents(".form-group").addClass("has-error"),$(this).parents(".form-element").addClass("has-error"),$("<span class='help-block cfpinvalido'>CPF inv\u00e1lido.</span>").insertAfter(this),$(this).val(""),$(".cpf").mask("?999.999.999-99"),
$(this).focus())});$(".cnpj").unbind("change");$(".cnpj").mask("?99.999.999/9999-99");$(".cnpj").bind("change",function(){$(this).parents(".form-group").removeClass("has-error");$(this).parents(".form-element").removeClass("has-error");$(".cnjpinvalido").remove();isCNPJ($(this).val())||($(this).parents(".form-group").addClass("has-error"),$(this).parents(".form-element").addClass("has-error"),$("<span class='help-block cnjpinvalido'>CNPJ inv\u00e1lido.</span>").insertAfter(this),$(this).val(""),$(".cnpj").mask("?99.999.999/9999-99"),
$(this).focus())});$(".cep").mask("99.999-999");$(".telefone").mask("(99) 99999999?99",{placeholder:" "});$(".numero").unbind("paste");$(".numero").keypress(function(a){var b=a.keyCode?a.keyCode:a.which,c="8,9,13,35,36,37".match(new RegExp(b));48<=b&&57>=b||c||a.preventDefault()}).bind({paste:function(){setTimeout(jQuery.proxy(function(){this.val(this.val().replace(/[^0-9]/g,""))},$(this)),0)}});$(".quantidade").unbind("paste");$(".quantidade").css("text-align","right").keypress(function(a){var b=
a.keyCode?a.keyCode:a.which,c="8,9,13,35,36,37".match(new RegExp(b));48<=b&&57>=b||c||a.preventDefault()}).bind({paste:function(){setTimeout(jQuery.proxy(function(){this.val(this.val().replace(/[^0-9]/g,""))},$(this)),0)}});$(".valor").maskValor();$(".caixa").unbind("keyup");$(".caixa").unbind("paste");$(".caixa").keyup(function(a){a=event.keyCode?event.keyCode:event.which;var b=$(this).attr("maxlength");49<=a&&57>=a&&$(this).val().length>=b&&(a=$(this).closest("form").find(":input:visible"),a.eq(a.index(this)+
1).focus())}).bind({paste:function(){setTimeout(jQuery.proxy(function(){var a=this.attr("maxlength");this.val().length>=a&&(a=$(".caixa"),a.eq(a.index(this)+1).focus())},$(this)),0)}});$(".metadado").keypress(function(a){var b=a.keyCode?a.keyCode:a.which,c="8,9,13,95".match(new RegExp(b));(65>b||90<b)&&(97>b||123<b)&&32!=b&&!c&&a.preventDefault()}).bind({paste:function(){setTimeout(jQuery.proxy(function(){this.val(this.val().replace(/[_\W]+/g,""))},$(this)),0)}});$("input[data-toggle='tooltip']").tooltip();
$("a[data-toggle='tooltip']").tooltip();$("textarea[data-toggle='tooltip']").tooltip();$(".modal:visible").each(function(){var a=$(this)[0].id;$(this).find(".btn-primary").clickOnEnter({element:a})})}function SetFocus(a){setTimeout(function(){$("#"+a).focus()},400)}
function isCPF(a){exp=/\.|\-/g;a=a.toString().replace(exp,"");var b=eval(a.charAt(9)+a.charAt(10)),c=0,d=0,e=11;for(i=0;9>i;i++)c+=eval(a.charAt(i)*(e-1)),d+=eval(a.charAt(i)*e),e--;c=10==10*c%11?0:10*c%11;return 10*c+10*(d+2*c)%11!=b?!1:!0}
function isCNPJ(a){var b=[6,5,4,3,2,9,8,7,6,5,4,3,2],c=new Number,d=new Number;exp=/\.|\-|\//g;a=a.toString().replace(exp,"");var e=new Number(eval(a.charAt(12)+a.charAt(13)));for(i=0;i<b.length;i++)c+=0<i?a.charAt(i-1)*b[i]:0,d+=a.charAt(i)*b[i];return 10*(2>c%11?0:11-c%11)+(2>d%11?0:11-d%11)!=e?!1:!0}
function isData(a){var b=parseInt(a.substring(0,2)),c=parseInt(a.substring(3,5))-1,d=parseInt(a.substring(6,10)),e=0,f=0;16==a.length&&(e=parseInt(a.substring(11,13)),f=parseInt(a.substring(14,16)));a=new Date(d,c,b,e,f);return a.getFullYear()==d&&a.getMonth()==c&&a.getDate()==Number(b)&&a.getHours()==e&&a.getMinutes()==f}
function isHora(a){var b=parseInt(a.substring(0,2));a=parseInt(a.substring(3,5));var c=new Date((new Date).getFullYear(),(new Date).getMonth(),(new Date).getDay(),b,a);return c.getHours()==b&&c.getMinutes()==a}function isEmail(a){return/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(a)}
function ToDate(a){return""!=a&&"undefined"!=typeof a?(a=a.split("/"),new Date(a[2],a[1]-1,a[0])):new Date}function StringToDate(a){var b=parseInt(a.substring(0,2)),c=parseInt(a.substring(3,5))-1,d=parseInt(a.substring(6,10)),e=0,f=0;16==a.length&&(e=parseInt(a.substring(11,13)),f=parseInt(a.substring(14,16)));return new Date(d,c,b,e,f)}function DateToMonthYear(a){a.getDate();var b=a.getMonth()+1;a=a.getFullYear();return b+"/"+a}
function GetMonth(a){return-1<a.indexOf("/")?(a=a.split("/")[0],0==a.indexOf("0")&&(a=a.replace("0","")),parseInt(a)-1):0}function GetYear(a){return-1<a.indexOf("/")?(a=a.split("/")[1],parseInt(a)):0}var current_zindex=1050;
function ShowModalDialog(a){$("#"+a).modal({show:!0,backdrop:"static",keyboard:!0});$("body").css("overflow","hidden");$(".modal-backdrop.fade.in:last-child").css("z-index",current_zindex);current_zindex+=10;$("#"+a).css("z-index",current_zindex);$("#"+a).find(".btn-primary").clickOnEnter({element:a})}
function ShowInnerModalDialog(a){$("#"+a).modal({show:!0,backdrop:"static",keyboard:!0});$("body").css("overflow","hidden");$("#"+a).parent().prepend($(".modal-backdrop.fade.in:last-child").detach());$(".modal-backdrop.fade.in:last-child").css("z-index",current_zindex);current_zindex+=10;$("#"+a).css("z-index",current_zindex)}function AppendModalDialogOnBody(a){$(document.body).append($("#"+a).detach())}
function HideModalDialog(a){$("#"+a).css("z-index");$("#"+a).modal("hide");setTimeout(function(){0==$(".modal:visible").length&&0<$(".modal-backdrop").length&&$(".modal-backdrop").remove();$(".modal:visible").css("overflow","auto")},400);1>=$(".modal-backdrop.fade.in").length&&$("body").css("overflow","auto")}
function getHtmlAlert(){return'<div id="dataAlertModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true"><div class="modal-dialog alert #css#"><h4>#Heading#</h4><p>#Body#</p><div class="modal-footer"><a class="btn btn-default" id="dataAlertOK">Fechar</a></div></div></div>'}
function ShowAlertaModal(a,b,c){$("#dataAlertModal").remove();var d=getHtmlAlert(),d=d.replace("#Heading#","").replace("#Body#",a).replace("#css#",c);$("body").append(d);ShowModalDialog("dataAlertModal");$("#dataAlertOK").click(function(){HideModalDialog("dataAlertModal");setTimeout(function(){"undefined"!=typeof b&&(window.location=b)},300)})}function AlertaSucesso(a,b){ShowAlertaModal(a,b,"alert-success")}function AlertaErro(a,b){ShowAlertaModal(a,b,"alert-danger")}
function AlertaValidacao(a,b){ShowAlertaModal(a,b,"alert-warning")}
function ShowReport(a){$("body").css("overflow","hidden");if(0==$("body").find("#dataReportModal").length){var b;b='<div id="dataReportModal" class="modal fade"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">\u00d7</button><h4 class="modal-title">#Heading#</h4></div><div id="reportBody" class="modal-body"></div></div></div></div>'.replace("#Heading#",a);$("body").append(b);$("#reportBody").append($("#report"));
$("#dataReportModal .modal-dialog").width("80%");$("#dataReportModal .modal-dialog").css("min-width","844px");$("#dataReportModal .modal-body").height($(window).height()-110);$("#dataReportModal .modal-dialog").css("margin-top","5px");$("#dataReportModal").css("overflow","hidden")}$("#dataReportModal .modal-title").text(a);$("#dataReportModal").modal({show:!0,backdrop:"static",outline:"none",top:"1"});$("#report").show();$("#dataReportModal .close").click(function(){$("#dataReportModal").modal("hide");
1>=$(".modal-backdrop.fade.in").length&&$("body").css("overflow","auto")})}function NotificacaoSucesso(a){return noty({text:a,type:"success",dismissQueue:!0,layout:"topCenter",theme:"defaultTheme",timeout:1E3})};